//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudDoctor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DOCTOREntities : DbContext
    {
        public DOCTOREntities()
            : base("name=DOCTOREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DOCTOR> TB_DOCTOR { get; set; }
        public virtual DbSet<TB_PARAMETERS> TB_PARAMETERS { get; set; }
        public virtual DbSet<TB_SPECIALITY> TB_SPECIALITY { get; set; }
        public virtual DbSet<TB_USERS> TB_USERS { get; set; }
    
        public virtual ObjectResult<SP_GET_Doctors_Result> SP_GET_Doctors(Nullable<int> doctorId)
        {
            var doctorIdParameter = doctorId.HasValue ?
                new ObjectParameter("DoctorId", doctorId) :
                new ObjectParameter("DoctorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_Doctors_Result>("SP_GET_Doctors", doctorIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_Parameters_Result> SP_GET_Parameters(Nullable<int> paramId)
        {
            var paramIdParameter = paramId.HasValue ?
                new ObjectParameter("ParamId", paramId) :
                new ObjectParameter("ParamId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_Parameters_Result>("SP_GET_Parameters", paramIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_Users_Result> SP_GET_Users(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_Users_Result>("SP_GET_Users", userIdParameter);
        }
    
        public virtual int SP_INS_Doctors(string dOCTORNAME, Nullable<System.DateTime> bORNDATE, string lOCATIONDOCTOR, string dESCRIPTION)
        {
            var dOCTORNAMEParameter = dOCTORNAME != null ?
                new ObjectParameter("DOCTORNAME", dOCTORNAME) :
                new ObjectParameter("DOCTORNAME", typeof(string));
    
            var bORNDATEParameter = bORNDATE.HasValue ?
                new ObjectParameter("BORNDATE", bORNDATE) :
                new ObjectParameter("BORNDATE", typeof(System.DateTime));
    
            var lOCATIONDOCTORParameter = lOCATIONDOCTOR != null ?
                new ObjectParameter("LOCATIONDOCTOR", lOCATIONDOCTOR) :
                new ObjectParameter("LOCATIONDOCTOR", typeof(string));
    
            var dESCRIPTIONParameter = dESCRIPTION != null ?
                new ObjectParameter("DESCRIPTION", dESCRIPTION) :
                new ObjectParameter("DESCRIPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_Doctors", dOCTORNAMEParameter, bORNDATEParameter, lOCATIONDOCTORParameter, dESCRIPTIONParameter);
        }
    
        public virtual int SP_INS_Users(string uSERNAME, string uSERPASSWORD, Nullable<System.DateTime> bORNDATE, string uSEREMAIL)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var uSERPASSWORDParameter = uSERPASSWORD != null ?
                new ObjectParameter("USERPASSWORD", uSERPASSWORD) :
                new ObjectParameter("USERPASSWORD", typeof(string));
    
            var bORNDATEParameter = bORNDATE.HasValue ?
                new ObjectParameter("BORNDATE", bORNDATE) :
                new ObjectParameter("BORNDATE", typeof(System.DateTime));
    
            var uSEREMAILParameter = uSEREMAIL != null ?
                new ObjectParameter("USEREMAIL", uSEREMAIL) :
                new ObjectParameter("USEREMAIL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_Users", uSERNAMEParameter, uSERPASSWORDParameter, bORNDATEParameter, uSEREMAILParameter);
        }
    
        public virtual int SP_UPD_Doctors(Nullable<int> doctroID, string dOCTORNAME, Nullable<System.DateTime> bORNDATE, string lOCATIONDOCTOR, string dESCRIPTION)
        {
            var doctroIDParameter = doctroID.HasValue ?
                new ObjectParameter("DoctroID", doctroID) :
                new ObjectParameter("DoctroID", typeof(int));
    
            var dOCTORNAMEParameter = dOCTORNAME != null ?
                new ObjectParameter("DOCTORNAME", dOCTORNAME) :
                new ObjectParameter("DOCTORNAME", typeof(string));
    
            var bORNDATEParameter = bORNDATE.HasValue ?
                new ObjectParameter("BORNDATE", bORNDATE) :
                new ObjectParameter("BORNDATE", typeof(System.DateTime));
    
            var lOCATIONDOCTORParameter = lOCATIONDOCTOR != null ?
                new ObjectParameter("LOCATIONDOCTOR", lOCATIONDOCTOR) :
                new ObjectParameter("LOCATIONDOCTOR", typeof(string));
    
            var dESCRIPTIONParameter = dESCRIPTION != null ?
                new ObjectParameter("DESCRIPTION", dESCRIPTION) :
                new ObjectParameter("DESCRIPTION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPD_Doctors", doctroIDParameter, dOCTORNAMEParameter, bORNDATEParameter, lOCATIONDOCTORParameter, dESCRIPTIONParameter);
        }
    
        public virtual int SP_UPD_Parameters(Nullable<int> iD_PARAM, string dESCR_PARAM, string vAL1, string vAL2, string vAL3)
        {
            var iD_PARAMParameter = iD_PARAM.HasValue ?
                new ObjectParameter("ID_PARAM", iD_PARAM) :
                new ObjectParameter("ID_PARAM", typeof(int));
    
            var dESCR_PARAMParameter = dESCR_PARAM != null ?
                new ObjectParameter("DESCR_PARAM", dESCR_PARAM) :
                new ObjectParameter("DESCR_PARAM", typeof(string));
    
            var vAL1Parameter = vAL1 != null ?
                new ObjectParameter("VAL1", vAL1) :
                new ObjectParameter("VAL1", typeof(string));
    
            var vAL2Parameter = vAL2 != null ?
                new ObjectParameter("VAL2", vAL2) :
                new ObjectParameter("VAL2", typeof(string));
    
            var vAL3Parameter = vAL3 != null ?
                new ObjectParameter("VAL3", vAL3) :
                new ObjectParameter("VAL3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPD_Parameters", iD_PARAMParameter, dESCR_PARAMParameter, vAL1Parameter, vAL2Parameter, vAL3Parameter);
        }
    }
}
